# configuration.yaml
application:
  port: 8080
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  timeout_milliseconds: 10000